spring.application.name=AIPredictionService

server.port=8085

spring.data.mongodb.uri=mongodb://localhost:27017/aipredictiondb

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1


# =====================================================
# EXISTING FLASK AI MODEL
# =====================================================

flask.api.url=http://localhost:5000/predict


# =====================================================
# EXISTING VITALS SERVICE
# =====================================================

vitals.api.url=http://localhost:8088


# =====================================================
# GEMINI - CARE PLAN ONLY
# =====================================================

gemini.api.key=YOUR_GEMINI_API_KEY

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent