import { FaRobot,FaHeartbeat,FaAppleAlt,FaRunning,FaUserMd,FaCheckCircle,FaBrain } from "react-icons/fa";
const recommendations=[
    {icon:<FaHeartbeat/>,title:"Cardiac Health",text:"Maintain blood pressure below 120/80 mmHg.",color:"#ef4444",priority:"High"},
    {icon:<FaAppleAlt/>,title:"Nutrition",text:"Increase vegetables and reduce sodium intake.",color:"#22c55e",priority:"Medium"},
    {icon:<FaRunning/>,title:"Exercise",text:"30 minutes of walking for 5 days a week.",color:"#3b82f6",priority:"Medium"},
    {icon:<FaUserMd/>,title:"Follow-up",text:"Schedule a cardiology review within 30 days.",color:"#f59e0b",priority:"High"}];
function AIRecommendations(){return(<div style={{marginTop:24,padding:24,borderRadius:24,background:"linear-gradient(135deg,#0f172a,#1e3a8a)",color:"#fff",boxShadow:"0 20px 40px rgba(0,0,0,.30)"}}>
    <div className="d-flex justify-content-between align-items-center mb-4"><div className="d-flex align-items-center gap-3"><div style={{width:60,height:60,borderRadius:"50%",background:"rgba(59,130,246,.2)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:28}}><FaRobot/></div><div><h3 className="mb-1 fw-bold">AI Clinical Recommendations</h3><small style={{color:"#cbd5e1"}}>Generated using predictive analytics</small></div></div><span className="badge bg-success px-3 py-2"><FaBrain className="me-2"/>AI Active</span></div>
    <div className="row g-4">{recommendations.map((i,k)=><div className="col-md-6" key={k}><div style={{background:"rgba(255,255,255,.08)",borderLeft:`5px solid ${i.color}`,borderRadius:18,padding:18,height:"100%"}}><div className="d-flex justify-content-between"><div style={{color:i.color,fontSize:28}}>{i.icon}</div><span style={{background:i.color,color:"#fff",padding:"4px 10px",borderRadius:20,fontSize:12,fontWeight:600}}>{i.priority}</span></div><h5 className="mt-3">{i.title}</h5><p style={{color:"#cbd5e1"}}>{i.text}</p><div className="d-flex align-items-center gap-2 mt-3"><FaCheckCircle color="#22c55e"/><small style={{color:"#86efac"}}>Recommended by AI Engine</small></div></div></div>)}</div>
    <div className="mt-4" style={{background:"rgba(34,197,94,.12)",borderRadius:18,padding:16}}><strong>AI Summary</strong><p className="mb-0 mt-2" style={{color:"#cbd5e1"}}>Overall patient condition is stable. Continue medication, maintain healthy nutrition, exercise regularly, and attend the scheduled cardiology follow-up.</p></div></div>);} export default AIRecommendations;